// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqiLgq5zsJTNqW6adhSvNhDGiEmfI_h2g',
    appId: '1:920851557868:web:aa522df7bd073e1ab7a4c9',
    messagingSenderId: '920851557868',
    projectId: 'hopesample-adf88',
    authDomain: 'hopesample-adf88.firebaseapp.com',
    storageBucket: 'hopesample-adf88.appspot.com',
    measurementId: 'G-CNGQKR1DHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04R-DgPbionbUR6fqw7hDKxSgI5y5lD8',
    appId: '1:920851557868:android:b02df2b423859802b7a4c9',
    messagingSenderId: '920851557868',
    projectId: 'hopesample-adf88',
    storageBucket: 'hopesample-adf88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtTllqmXqkljskbkOqHYNNw1FAYaMmIs',
    appId: '1:920851557868:ios:3e16d0aa2e003bc1b7a4c9',
    messagingSenderId: '920851557868',
    projectId: 'hopesample-adf88',
    storageBucket: 'hopesample-adf88.appspot.com',
    iosBundleId: 'com.example.hopehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQtTllqmXqkljskbkOqHYNNw1FAYaMmIs',
    appId: '1:920851557868:ios:33c26f300cce2d6db7a4c9',
    messagingSenderId: '920851557868',
    projectId: 'hopesample-adf88',
    storageBucket: 'hopesample-adf88.appspot.com',
    iosBundleId: 'com.example.hopehub.RunnerTests',
  );
}
